--------------------------------------------------------
--  File created - Friday-December-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCEPTED_TO_PROJECT
--------------------------------------------------------

  CREATE TABLE "UBD441"."ACCEPTED_TO_PROJECT" 
   (	"ACTIVITY_ACTIVITY_ID" NUMBER, 
	"STUDENT_EMAIL" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TS_ALUMNOS"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table ACTIVITY
--------------------------------------------------------

  CREATE TABLE "UBD441"."ACTIVITY" 
   (	"START_DATE" DATE, 
	"ACTIVITY_ID" NUMBER, 
	"NAME" VARCHAR2(80 BYTE), 
	"DESCRIPTION" CLOB, 
	"AVAILABLE_SPOTS" NUMBER, 
	"EMAIL" VARCHAR2(80 BYTE), 
	"PHONE" VARCHAR2(12 BYTE), 
	"WEBSITE" VARCHAR2(80 BYTE), 
	"END_DATE" DATE, 
	"CREATED_AT" DATE, 
	"IS_VOLUNTEERING" CHAR(1 BYTE), 
	"ORGANIZATION_EMAIL" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"   NO INMEMORY 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "TS_ALUMNOS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table APPLICANT_TO_PROJECT
--------------------------------------------------------

  CREATE TABLE "UBD441"."APPLICANT_TO_PROJECT" 
   (	"ACTIVITY_ACTIVITY_ID" NUMBER, 
	"STUDENT_EMAIL" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TS_ALUMNOS"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table ASSIGNED_TO_STUDENT
--------------------------------------------------------

  CREATE TABLE "UBD441"."ASSIGNED_TO_STUDENT" 
   (	"STUDENT_EMAIL" VARCHAR2(80 BYTE), 
	"ACTIVITY_ACTIVITY_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TS_ALUMNOS"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table GRADE
--------------------------------------------------------

  CREATE TABLE "UBD441"."GRADE" 
   (	"SCORE" NUMBER, 
	"DESCRIPTION" CLOB, 
	"TEACHER_EMAIL" VARCHAR2(80 BYTE), 
	"STUDENT_EMAIL" VARCHAR2(80 BYTE), 
	"ACTIVITY_ACTIVITY_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"   NO INMEMORY 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "TS_ALUMNOS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ORGANIZATION
--------------------------------------------------------

  CREATE TABLE "UBD441"."ORGANIZATION" 
   (	"EMAIL" VARCHAR2(80 BYTE), 
	"TYPE" VARCHAR2(80 BYTE), 
	"DESCRIPTION" CLOB, 
	"PHONE" VARCHAR2(12 BYTE), 
	"WEBSITE" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"   NO INMEMORY 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "TS_ALUMNOS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "UBD441"."PERSON" 
   (	"EMAIL" VARCHAR2(80 BYTE), 
	"FACULTY" VARCHAR2(80 BYTE), 
	"UNIVERSITY" VARCHAR2(80 BYTE), 
	"BIO" CLOB, 
	"SURNAMES" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"   NO INMEMORY 
 LOB ("BIO") STORE AS SECUREFILE (
  TABLESPACE "TS_ALUMNOS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "UBD441"."REVIEW" 
   (	"TITLE" VARCHAR2(80 BYTE), 
	"TEXT" CLOB, 
	"COORDINATION_MARK" NUMBER, 
	"RESPONSIVENESS_MARK" NUMBER, 
	"USEFULNESS_MARK" NUMBER, 
	"CREATED_AT" DATE, 
	"STUDENT_EMAIL" VARCHAR2(80 BYTE), 
	"ACTIVITY_ACTIVITY_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"   NO INMEMORY 
 LOB ("TEXT") STORE AS SECUREFILE (
  TABLESPACE "TS_ALUMNOS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SKILL
--------------------------------------------------------

  CREATE TABLE "UBD441"."SKILL" 
   (	"NAME" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table SKILL_TO_STUDENT
--------------------------------------------------------

  CREATE TABLE "UBD441"."SKILL_TO_STUDENT" 
   (	"SKILL_NAME" VARCHAR2(80 BYTE), 
	"STUDENT_EMAIL" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TS_ALUMNOS"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "UBD441"."STUDENT" 
   (	"EMAIL" VARCHAR2(80 BYTE), 
	"ENROLLMENT_DATE" DATE, 
	"AVAILABILITY_START_HOUR" NUMBER, 
	"AVAILABILITY_END_HOUR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table TEACHER
--------------------------------------------------------

  CREATE TABLE "UBD441"."TEACHER" 
   (	"EMAIL" VARCHAR2(80 BYTE), 
	"WEBSITE" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table USER
--------------------------------------------------------

  CREATE TABLE "UBD441"."USER" 
   (	"EMAIL" VARCHAR2(80 BYTE), 
	"NAME" VARCHAR2(80 BYTE), 
	"PASSWORD_HASH" VARCHAR2(80 BYTE), 
	"PIRCTURE" BLOB, 
	"CREATED_AT" DATE, 
	"LAST_LOGIN_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"   NO INMEMORY 
 LOB ("PIRCTURE") STORE AS SECUREFILE (
  TABLESPACE "TS_ALUMNOS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into UBD441.ACCEPTED_TO_PROJECT
SET DEFINE OFF;
REM INSERTING into UBD441.ACTIVITY
SET DEFINE OFF;
Insert into UBD441.ACTIVITY (START_DATE,ACTIVITY_ID,NAME,AVAILABLE_SPOTS,EMAIL,PHONE,WEBSITE,END_DATE,CREATED_AT,IS_VOLUNTEERING,ORGANIZATION_EMAIL) values (to_date('16-DEC-19','DD-MON-RR'),1,'Final activity',10,'activity@example.com','999666666','web.com',to_date('17-DEC-19','DD-MON-RR'),to_date('10-DEC-19','DD-MON-RR'),'1','what@example.com');
Insert into UBD441.ACTIVITY (START_DATE,ACTIVITY_ID,NAME,AVAILABLE_SPOTS,EMAIL,PHONE,WEBSITE,END_DATE,CREATED_AT,IS_VOLUNTEERING,ORGANIZATION_EMAIL) values (to_date('08-DEC-19','DD-MON-RR'),2,'Second',15,'activity2@example.com','123123123','web2.com',to_date('30-DEC-19','DD-MON-RR'),to_date('17-DEC-19','DD-MON-RR'),'0','what@example.com');
REM INSERTING into UBD441.APPLICANT_TO_PROJECT
SET DEFINE OFF;
REM INSERTING into UBD441.ASSIGNED_TO_STUDENT
SET DEFINE OFF;
REM INSERTING into UBD441.GRADE
SET DEFINE OFF;
Insert into UBD441.GRADE (SCORE,TEACHER_EMAIL,STUDENT_EMAIL,ACTIVITY_ACTIVITY_ID) values (5,'teacher@example.com','student@example.com',1);
REM INSERTING into UBD441.ORGANIZATION
SET DEFINE OFF;
Insert into UBD441.ORGANIZATION (EMAIL,TYPE,PHONE,WEBSITE) values ('what@example.com','NGO','123456789','web.com');
REM INSERTING into UBD441.PERSON
SET DEFINE OFF;
Insert into UBD441.PERSON (EMAIL,FACULTY,UNIVERSITY,SURNAMES) values ('teacher@example.com','Whatever','UMA','One two three');
Insert into UBD441.PERSON (EMAIL,FACULTY,UNIVERSITY,SURNAMES) values ('student@example.com','Not whatever','UMA','FOur five six');
REM INSERTING into UBD441.REVIEW
SET DEFINE OFF;
Insert into UBD441.REVIEW (TITLE,COORDINATION_MARK,RESPONSIVENESS_MARK,USEFULNESS_MARK,CREATED_AT,STUDENT_EMAIL,ACTIVITY_ACTIVITY_ID) values ('Incredible projec',10,10,10,to_date('09-DEC-19','DD-MON-RR'),'student@example.com',1);
REM INSERTING into UBD441.SKILL
SET DEFINE OFF;
Insert into UBD441.SKILL (NAME) values ('Databases');
Insert into UBD441.SKILL (NAME) values ('Escalada');
Insert into UBD441.SKILL (NAME) values ('Jumping');
REM INSERTING into UBD441.SKILL_TO_STUDENT
SET DEFINE OFF;
REM INSERTING into UBD441.STUDENT
SET DEFINE OFF;
Insert into UBD441.STUDENT (EMAIL,ENROLLMENT_DATE,AVAILABILITY_START_HOUR,AVAILABILITY_END_HOUR) values ('student@example.com',to_date('10-DEC-19','DD-MON-RR'),12,16);
REM INSERTING into UBD441.TEACHER
SET DEFINE OFF;
Insert into UBD441.TEACHER (EMAIL,WEBSITE) values ('teacher@example.com','web.com');
REM INSERTING into UBD441."USER"
SET DEFINE OFF;
Insert into UBD441."USER" (EMAIL,NAME,PASSWORD_HASH,CREATED_AT,LAST_LOGIN_AT) values ('what@example.com','Lorenzo','ejhfrq37uhdsdhgf7yu',to_date('26-DEC-19','DD-MON-RR'),to_date('27-DEC-19','DD-MON-RR'));
Insert into UBD441."USER" (EMAIL,NAME,PASSWORD_HASH,CREATED_AT,LAST_LOGIN_AT) values ('what2@example2.com','Alvaro','askhdui12e9forvbuywadgho',to_date('08-DEC-19','DD-MON-RR'),to_date('31-DEC-19','DD-MON-RR'));
Insert into UBD441."USER" (EMAIL,NAME,PASSWORD_HASH,CREATED_AT,LAST_LOGIN_AT) values ('teacher@example.com','Enciso','ksudho9ej98dh09sd',to_date('17-DEC-19','DD-MON-RR'),to_date('24-DEC-19','DD-MON-RR'));
Insert into UBD441."USER" (EMAIL,NAME,PASSWORD_HASH,CREATED_AT,LAST_LOGIN_AT) values ('student@example.com','Antonio','2ueh9jd0as8hd98q2',to_date('22-DEC-19','DD-MON-RR'),to_date('31-DEC-19','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index ACCEPTED_TO_PROJECT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBD441"."ACCEPTED_TO_PROJECT_PK" ON "UBD441"."ACCEPTED_TO_PROJECT" ("ACTIVITY_ACTIVITY_ID", "STUDENT_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index ACTIVITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBD441"."ACTIVITY_PK" ON "UBD441"."ACTIVITY" ("ACTIVITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index APPLICANT_TO_PROJECT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBD441"."APPLICANT_TO_PROJECT_PK" ON "UBD441"."APPLICANT_TO_PROJECT" ("ACTIVITY_ACTIVITY_ID", "STUDENT_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index RELATION_3_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBD441"."RELATION_3_PK" ON "UBD441"."ASSIGNED_TO_STUDENT" ("STUDENT_EMAIL", "ACTIVITY_ACTIVITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index GRADE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBD441"."GRADE_PK" ON "UBD441"."GRADE" ("TEACHER_EMAIL", "STUDENT_EMAIL", "ACTIVITY_ACTIVITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index ORGANIZATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBD441"."ORGANIZATION_PK" ON "UBD441"."ORGANIZATION" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index PERSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBD441"."PERSON_PK" ON "UBD441"."PERSON" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index REVIEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBD441"."REVIEW_PK" ON "UBD441"."REVIEW" ("STUDENT_EMAIL", "ACTIVITY_ACTIVITY_ID", "CREATED_AT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index SKILL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBD441"."SKILL_PK" ON "UBD441"."SKILL" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index SKILL_TO_STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBD441"."SKILL_TO_STUDENT_PK" ON "UBD441"."SKILL_TO_STUDENT" ("SKILL_NAME", "STUDENT_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBD441"."STUDENT_PK" ON "UBD441"."STUDENT" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index TEACHER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBD441"."TEACHER_PK" ON "UBD441"."TEACHER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBD441"."USER_PK" ON "UBD441"."USER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  Constraints for Table ACCEPTED_TO_PROJECT
--------------------------------------------------------

  ALTER TABLE "UBD441"."ACCEPTED_TO_PROJECT" ADD CONSTRAINT "ACCEPTED_TO_PROJECT_PK" PRIMARY KEY ("ACTIVITY_ACTIVITY_ID", "STUDENT_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS_ALUMNOS"  ENABLE;
  ALTER TABLE "UBD441"."ACCEPTED_TO_PROJECT" MODIFY ("ACTIVITY_ACTIVITY_ID" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."ACCEPTED_TO_PROJECT" MODIFY ("STUDENT_EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACTIVITY
--------------------------------------------------------

  ALTER TABLE "UBD441"."ACTIVITY" ADD CONSTRAINT "ACTIVITY_PK" PRIMARY KEY ("ACTIVITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
  ALTER TABLE "UBD441"."ACTIVITY" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."ACTIVITY" MODIFY ("ACTIVITY_ID" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."ACTIVITY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."ACTIVITY" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."ACTIVITY" MODIFY ("AVAILABLE_SPOTS" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."ACTIVITY" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."ACTIVITY" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."ACTIVITY" MODIFY ("IS_VOLUNTEERING" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."ACTIVITY" MODIFY ("ORGANIZATION_EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPLICANT_TO_PROJECT
--------------------------------------------------------

  ALTER TABLE "UBD441"."APPLICANT_TO_PROJECT" ADD CONSTRAINT "APPLICANT_TO_PROJECT_PK" PRIMARY KEY ("ACTIVITY_ACTIVITY_ID", "STUDENT_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS_ALUMNOS"  ENABLE;
  ALTER TABLE "UBD441"."APPLICANT_TO_PROJECT" MODIFY ("ACTIVITY_ACTIVITY_ID" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."APPLICANT_TO_PROJECT" MODIFY ("STUDENT_EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASSIGNED_TO_STUDENT
--------------------------------------------------------

  ALTER TABLE "UBD441"."ASSIGNED_TO_STUDENT" ADD CONSTRAINT "RELATION_3_PK" PRIMARY KEY ("STUDENT_EMAIL", "ACTIVITY_ACTIVITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS_ALUMNOS"  ENABLE;
  ALTER TABLE "UBD441"."ASSIGNED_TO_STUDENT" MODIFY ("STUDENT_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."ASSIGNED_TO_STUDENT" MODIFY ("ACTIVITY_ACTIVITY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRADE
--------------------------------------------------------

  ALTER TABLE "UBD441"."GRADE" ADD CONSTRAINT "GRADE_PK" PRIMARY KEY ("TEACHER_EMAIL", "STUDENT_EMAIL", "ACTIVITY_ACTIVITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
  ALTER TABLE "UBD441"."GRADE" MODIFY ("SCORE" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."GRADE" MODIFY ("TEACHER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."GRADE" MODIFY ("STUDENT_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."GRADE" MODIFY ("ACTIVITY_ACTIVITY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORGANIZATION
--------------------------------------------------------

  ALTER TABLE "UBD441"."ORGANIZATION" ADD CONSTRAINT "ORGANIZATION_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
  ALTER TABLE "UBD441"."ORGANIZATION" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."ORGANIZATION" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."ORGANIZATION" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "UBD441"."PERSON" ADD CONSTRAINT "PERSON_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
  ALTER TABLE "UBD441"."PERSON" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."PERSON" MODIFY ("FACULTY" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."PERSON" MODIFY ("UNIVERSITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "UBD441"."REVIEW" ADD CONSTRAINT "REVIEW_PK" PRIMARY KEY ("STUDENT_EMAIL", "ACTIVITY_ACTIVITY_ID", "CREATED_AT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
  ALTER TABLE "UBD441"."REVIEW" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."REVIEW" MODIFY ("TEXT" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."REVIEW" MODIFY ("COORDINATION_MARK" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."REVIEW" MODIFY ("RESPONSIVENESS_MARK" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."REVIEW" MODIFY ("USEFULNESS_MARK" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."REVIEW" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."REVIEW" MODIFY ("STUDENT_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."REVIEW" MODIFY ("ACTIVITY_ACTIVITY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SKILL
--------------------------------------------------------

  ALTER TABLE "UBD441"."SKILL" ADD CONSTRAINT "SKILL_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
  ALTER TABLE "UBD441"."SKILL" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SKILL_TO_STUDENT
--------------------------------------------------------

  ALTER TABLE "UBD441"."SKILL_TO_STUDENT" ADD CONSTRAINT "SKILL_TO_STUDENT_PK" PRIMARY KEY ("SKILL_NAME", "STUDENT_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS_ALUMNOS"  ENABLE;
  ALTER TABLE "UBD441"."SKILL_TO_STUDENT" MODIFY ("SKILL_NAME" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."SKILL_TO_STUDENT" MODIFY ("STUDENT_EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "UBD441"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
  ALTER TABLE "UBD441"."STUDENT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."STUDENT" MODIFY ("ENROLLMENT_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEACHER
--------------------------------------------------------

  ALTER TABLE "UBD441"."TEACHER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."TEACHER" ADD CONSTRAINT "TEACHER_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER
--------------------------------------------------------

  ALTER TABLE "UBD441"."USER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."USER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."USER" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."USER" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "UBD441"."USER" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCEPTED_TO_PROJECT
--------------------------------------------------------

  ALTER TABLE "UBD441"."ACCEPTED_TO_PROJECT" ADD CONSTRAINT "ACCEPTED_TO_PROJECT_ACTIVITY_FK" FOREIGN KEY ("ACTIVITY_ACTIVITY_ID")
	  REFERENCES "UBD441"."ACTIVITY" ("ACTIVITY_ID") ENABLE;
  ALTER TABLE "UBD441"."ACCEPTED_TO_PROJECT" ADD CONSTRAINT "ACCEPTED_TO_PROJECT_STUDENT_FK" FOREIGN KEY ("STUDENT_EMAIL")
	  REFERENCES "UBD441"."STUDENT" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACTIVITY
--------------------------------------------------------

  ALTER TABLE "UBD441"."ACTIVITY" ADD CONSTRAINT "ACTIVITY_ORGANIZATION_FK" FOREIGN KEY ("ORGANIZATION_EMAIL")
	  REFERENCES "UBD441"."ORGANIZATION" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APPLICANT_TO_PROJECT
--------------------------------------------------------

  ALTER TABLE "UBD441"."APPLICANT_TO_PROJECT" ADD CONSTRAINT "APPLICANT_TO_PROJECT_ACTIVITY_FK" FOREIGN KEY ("ACTIVITY_ACTIVITY_ID")
	  REFERENCES "UBD441"."ACTIVITY" ("ACTIVITY_ID") ENABLE;
  ALTER TABLE "UBD441"."APPLICANT_TO_PROJECT" ADD CONSTRAINT "APPLICANT_TO_PROJECT_STUDENT_FK" FOREIGN KEY ("STUDENT_EMAIL")
	  REFERENCES "UBD441"."STUDENT" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASSIGNED_TO_STUDENT
--------------------------------------------------------

  ALTER TABLE "UBD441"."ASSIGNED_TO_STUDENT" ADD CONSTRAINT "RELATION_3_ACTIVITY_FK" FOREIGN KEY ("ACTIVITY_ACTIVITY_ID")
	  REFERENCES "UBD441"."ACTIVITY" ("ACTIVITY_ID") ENABLE;
  ALTER TABLE "UBD441"."ASSIGNED_TO_STUDENT" ADD CONSTRAINT "RELATION_3_STUDENT_FK" FOREIGN KEY ("STUDENT_EMAIL")
	  REFERENCES "UBD441"."STUDENT" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRADE
--------------------------------------------------------

  ALTER TABLE "UBD441"."GRADE" ADD CONSTRAINT "GRADE_ACTIVITY_FK" FOREIGN KEY ("ACTIVITY_ACTIVITY_ID")
	  REFERENCES "UBD441"."ACTIVITY" ("ACTIVITY_ID") ENABLE;
  ALTER TABLE "UBD441"."GRADE" ADD CONSTRAINT "GRADE_STUDENT_FK" FOREIGN KEY ("STUDENT_EMAIL")
	  REFERENCES "UBD441"."STUDENT" ("EMAIL") ENABLE;
  ALTER TABLE "UBD441"."GRADE" ADD CONSTRAINT "GRADE_TEACHER_FK" FOREIGN KEY ("TEACHER_EMAIL")
	  REFERENCES "UBD441"."TEACHER" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORGANIZATION
--------------------------------------------------------

  ALTER TABLE "UBD441"."ORGANIZATION" ADD CONSTRAINT "ORGANIZATION_USER_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "UBD441"."USER" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "UBD441"."PERSON" ADD CONSTRAINT "PERSON_USER_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "UBD441"."USER" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "UBD441"."REVIEW" ADD CONSTRAINT "REVIEW_ACTIVITY_FK" FOREIGN KEY ("ACTIVITY_ACTIVITY_ID")
	  REFERENCES "UBD441"."ACTIVITY" ("ACTIVITY_ID") ENABLE;
  ALTER TABLE "UBD441"."REVIEW" ADD CONSTRAINT "REVIEW_STUDENT_FK" FOREIGN KEY ("STUDENT_EMAIL")
	  REFERENCES "UBD441"."STUDENT" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SKILL_TO_STUDENT
--------------------------------------------------------

  ALTER TABLE "UBD441"."SKILL_TO_STUDENT" ADD CONSTRAINT "SKILL_TO_STUDENT_SKILL_FK" FOREIGN KEY ("SKILL_NAME")
	  REFERENCES "UBD441"."SKILL" ("NAME") ENABLE;
  ALTER TABLE "UBD441"."SKILL_TO_STUDENT" ADD CONSTRAINT "SKILL_TO_STUDENT_STUDENT_FK" FOREIGN KEY ("STUDENT_EMAIL")
	  REFERENCES "UBD441"."STUDENT" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "UBD441"."STUDENT" ADD CONSTRAINT "STUDENT_PERSON_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "UBD441"."PERSON" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEACHER
--------------------------------------------------------

  ALTER TABLE "UBD441"."TEACHER" ADD CONSTRAINT "TEACHER_PERSON_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "UBD441"."PERSON" ("EMAIL") ENABLE;
