-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-12-13 14:14:20 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE accepted_to_project (
    activity_activity_id   NUMBER NOT NULL,
    student_email          VARCHAR2(80) NOT NULL
);

ALTER TABLE accepted_to_project ADD CONSTRAINT accepted_to_project_pk PRIMARY KEY ( activity_activity_id,
                                                                                    student_email );

CREATE TABLE activity (
    start_date           DATE NOT NULL,
    activity_id          NUMBER NOT NULL,
    name                 VARCHAR2(80) NOT NULL,
    description          CLOB NOT NULL,
    available_spots      NUMBER NOT NULL,
    email                VARCHAR2(80),
    phone                VARCHAR2(12),
    website              VARCHAR2(80),
    end_date             DATE NOT NULL,
    created_at           DATE NOT NULL,
    is_volunteering      CHAR(1) NOT NULL,
    organization_email   VARCHAR2(80) NOT NULL
);

ALTER TABLE activity ADD CONSTRAINT activity_pk PRIMARY KEY ( activity_id );

CREATE TABLE applicant_to_project (
    activity_activity_id   NUMBER NOT NULL,
    student_email          VARCHAR2(80) NOT NULL
);

ALTER TABLE applicant_to_project ADD CONSTRAINT applicant_to_project_pk PRIMARY KEY ( activity_activity_id,
                                                                                      student_email );

CREATE TABLE assigned_to_student (
    student_email          VARCHAR2(80) NOT NULL,
    activity_activity_id   NUMBER NOT NULL
);

ALTER TABLE assigned_to_student ADD CONSTRAINT relation_3_pk PRIMARY KEY ( student_email,
                                                                           activity_activity_id );

CREATE TABLE grade (
    score                  NUMBER NOT NULL,
    description            CLOB,
    teacher_email          VARCHAR2(80) NOT NULL,
    student_email          VARCHAR2(80) NOT NULL,
    activity_activity_id   NUMBER NOT NULL
);

ALTER TABLE grade
    ADD CONSTRAINT grade_pk PRIMARY KEY ( teacher_email,
                                          student_email,
                                          activity_activity_id );

CREATE TABLE organization (
    email         VARCHAR2(80) NOT NULL,
    type          VARCHAR2(80) NOT NULL,
    description   CLOB NOT NULL,
    phone         VARCHAR2(12),
    website       VARCHAR2(80)
);

ALTER TABLE organization ADD CONSTRAINT organization_pk PRIMARY KEY ( email );

CREATE TABLE person (
    email        VARCHAR2(80) NOT NULL,
    faculty      VARCHAR2(80) NOT NULL,
    university   VARCHAR2(80) NOT NULL,
    bio          CLOB,
    surnames     VARCHAR2(1000)
);

ALTER TABLE person ADD CONSTRAINT person_pk PRIMARY KEY ( email );

CREATE TABLE review (
    title                  VARCHAR2(80) NOT NULL,
    text                   CLOB NOT NULL,
    coordination_mark      NUMBER NOT NULL,
    responsiveness_mark    NUMBER NOT NULL,
    usefulness_mark        NUMBER NOT NULL,
    created_at             DATE NOT NULL,
    student_email          VARCHAR2(80) NOT NULL,
    activity_activity_id   NUMBER NOT NULL
);

ALTER TABLE review
    ADD CONSTRAINT review_pk PRIMARY KEY ( student_email,
                                           activity_activity_id,
                                           created_at );

CREATE TABLE skill (
    name VARCHAR2(80) NOT NULL
);

ALTER TABLE skill ADD CONSTRAINT skill_pk PRIMARY KEY ( name );

CREATE TABLE skill_to_student (
    skill_name      VARCHAR2(80) NOT NULL,
    student_email   VARCHAR2(80) NOT NULL
);

ALTER TABLE skill_to_student ADD CONSTRAINT skill_to_student_pk PRIMARY KEY ( skill_name,
                                                                              student_email );

CREATE TABLE student (
    email                     VARCHAR2(80) NOT NULL,
    enrollment_date           DATE NOT NULL,
    availability_start_hour   NUMBER,
    availability_end_hour     NUMBER
);

ALTER TABLE student ADD CONSTRAINT student_pk PRIMARY KEY ( email );

CREATE TABLE teacher (
    email     VARCHAR2(80) NOT NULL,
    website   VARCHAR2(80)
);

ALTER TABLE teacher ADD CONSTRAINT teacher_pk PRIMARY KEY ( email );

CREATE TABLE "USER" (
    email           VARCHAR2(80) NOT NULL,
    name            VARCHAR2(80) NOT NULL,
    password_hash   VARCHAR2(80) NOT NULL,
    pircture        BLOB,
    created_at      DATE NOT NULL,
    last_login_at   DATE
);

ALTER TABLE "USER" ADD CONSTRAINT user_pk PRIMARY KEY ( email );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE accepted_to_project
    ADD CONSTRAINT accepted_to_project_activity_fk FOREIGN KEY ( activity_activity_id )
        REFERENCES activity ( activity_id );

ALTER TABLE accepted_to_project
    ADD CONSTRAINT accepted_to_project_student_fk FOREIGN KEY ( student_email )
        REFERENCES student ( email );

ALTER TABLE activity
    ADD CONSTRAINT activity_organization_fk FOREIGN KEY ( organization_email )
        REFERENCES organization ( email );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE applicant_to_project
    ADD CONSTRAINT applicant_to_project_activity_fk FOREIGN KEY ( activity_activity_id )
        REFERENCES activity ( activity_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE applicant_to_project
    ADD CONSTRAINT applicant_to_project_student_fk FOREIGN KEY ( student_email )
        REFERENCES student ( email );

ALTER TABLE grade
    ADD CONSTRAINT grade_activity_fk FOREIGN KEY ( activity_activity_id )
        REFERENCES activity ( activity_id );

ALTER TABLE grade
    ADD CONSTRAINT grade_student_fk FOREIGN KEY ( student_email )
        REFERENCES student ( email );

ALTER TABLE grade
    ADD CONSTRAINT grade_teacher_fk FOREIGN KEY ( teacher_email )
        REFERENCES teacher ( email );

ALTER TABLE organization
    ADD CONSTRAINT organization_user_fk FOREIGN KEY ( email )
        REFERENCES "USER" ( email );

ALTER TABLE person
    ADD CONSTRAINT person_user_fk FOREIGN KEY ( email )
        REFERENCES "USER" ( email );

ALTER TABLE assigned_to_student
    ADD CONSTRAINT relation_3_activity_fk FOREIGN KEY ( activity_activity_id )
        REFERENCES activity ( activity_id );

ALTER TABLE assigned_to_student
    ADD CONSTRAINT relation_3_student_fk FOREIGN KEY ( student_email )
        REFERENCES student ( email );

ALTER TABLE review
    ADD CONSTRAINT review_activity_fk FOREIGN KEY ( activity_activity_id )
        REFERENCES activity ( activity_id );

ALTER TABLE review
    ADD CONSTRAINT review_student_fk FOREIGN KEY ( student_email )
        REFERENCES student ( email );

ALTER TABLE skill_to_student
    ADD CONSTRAINT skill_to_student_skill_fk FOREIGN KEY ( skill_name )
        REFERENCES skill ( name );

ALTER TABLE skill_to_student
    ADD CONSTRAINT skill_to_student_student_fk FOREIGN KEY ( student_email )
        REFERENCES student ( email );

ALTER TABLE student
    ADD CONSTRAINT student_person_fk FOREIGN KEY ( email )
        REFERENCES person ( email );

ALTER TABLE teacher
    ADD CONSTRAINT teacher_person_fk FOREIGN KEY ( email )
        REFERENCES person ( email );


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             31
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   7
-- WARNINGS                                 0
